[project]
name = "aidsplit"
description = "Enterprise donation and payroll distribution platform"
version = "1.0.0"
authors = ["AidSplit Team"]
telemetry = false
cache_dir = ".clarinet"
requirements = []

[contracts.distribution-engine-v4]
path = "contracts/distribution-engine-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.campaign-manager-v4]
path = "contracts/campaign-manager-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.hierarchy-calculator-v4]
path = "contracts/hierarchy-calculator-v3.clar" 
clarity_version = 2
epoch = 2.4

[contracts.nft-receipts-v4]
path = "contracts/nft-receipts-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.access-control-v4]
path = "contracts/access-control-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.company-auth-v4]
path = "contracts/company-auth-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.donation-targeting-v4]
path = "contracts/donation-targeting-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.nft-generator-v4]
path = "contracts/nft-generator-v3.clar"
clarity_version = 2
epoch = 2.4

[contracts.fundraising-campaign]
path = "contracts/fundraising-campaign.clar"
clarity_version = 2
epoch = 2.4

# Test accounts with proper STX balances
[[project.accounts]]
name = "deployer"
address = "STDTF2Q74P3FWMP4DT6D9SW8G6FY293XVP6G8RPM"
balance = 100000000000000  # 100M STX

[[project.accounts]]
name = "wallet_1" 
address = "ST2CY5V39NHDPWSXMW9QDT3HC3GD6Q6XX4CFRK9AG"
balance = 100000000000000

[[project.accounts]]
name = "wallet_2"
address = "ST2JHG361ZXG51QTKY2NQCVBPPRRE2KZB1HR05NNC" 
balance = 100000000000000

[[project.accounts]]
name = "wallet_3"
address = "ST3NBRSFKX28FQ2ZJ1MAKX58HKHSDGNV5N7R21XCP"
balance = 100000000000000

[[project.accounts]]
name = "wallet_4"
address = "ST2REHHS5J3CERCRBEPMGH7921Q6PYKAADT7JP2VB"
balance = 100000000000000

[repl]
costs = true
parser_version = 2